project:
  type: book

jupyter:
  kernel: ds-aa-cub-hurricanes

book:
  title: "Anticipatory Action - Cuba Hurricanes"
  author: "OCHA Centre for Humanitarian Data"
  date: "13/05/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - zma.qmd
    - ibtracs.qmd
    - imerg.qmd
    - chirps_gefs.qmd
    - combine_imerg_ibtracs.qmd
    - plot_optimization.qmd
    - era5_soil_moisture.qmd
    - threestage_trig_plot.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: true
    number-depth: 3
    fig-format: "png" # More efficient than SVG for most plots
    fig-dpi: 96       # Lower DPI for faster rendering
    self-contained: false # Avoid embedding all resources for faster builds
    embed-resources: false
    toc: true          # Enable table of contents for navigation
    css: custom.css    # Apply the custom CSS globally
    toc-depth: 3
    code-fold: true
    smooth-scroll: true

execute:
  freeze: auto        # Freeze execution to avoid re-running code chunks
  cache: false         # Enable caching for faster re-renders

editor: source
